"""add_tenant_api_keys

Revision ID: 1725bad5994c
Revises: a3f92b1cd045
Create Date: 2026-04-22 11:44:25.200424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1725bad5994c'
down_revision: Union[str, Sequence[str], None] = 'a3f92b1cd045'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=100), server_default='default', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    with op.batch_alter_table('tenant_api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_api_keys_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenant_api_keys_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_api_keys_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_tenant_api_keys_id'))

    op.drop_table('tenant_api_keys')
    # ### end Alembic commands ###
